### PR TITLE
#672 small fix

### LINKED ISSUE #672: Add link to description page for  `Protected by Adguard for Windows` menu item
image

https://adguard.com/adguard-adblock-browser-extension/integration-mode.html

### PR DESCRIPTION
**Pull request by Mizzick**
#672

### CODE REVIEW

File: Extension/lib/ui-service.js [hunk 1]
```diff
@@ -524,6 +527,10 @@ adguard.ui = (function (adguard) { // jshint ignore:line
         });
     };
 
+    var openIntegrationModeInfo = function () {
+        openTab('https://adguard.com/adguard-adblock-browser-extension/integration-mode.html#integrationMode');
```
Comment (atropnikov) [inline Extension/lib/ui-service.js]: Please, add `?utm_source=extension&aid=16593` parameters.

Comment (Mizzick) [inline Extension/lib/ui-service.js]: done
