### PR TITLE
Fix #510 safari converter

### LINKED ISSUE #510: Safari Content Blocker Problem
This part of code doesn't work correct
```
_createUrlFilterString: function (filter) {
    if (filter.urlRegExp) {
        return filter.urlRegExp.source;
    }

    if (filter.getUrlRuleText() == '||*') {
        return URL_FILTER_ANY_URL;
    }
    
    var urlRegExpSource = filter.getUrlRegExpSource();
    if (urlRegExpSource) {
        return urlRegExpSource;
    }

    // Rule with empty regexp
    return URL_FILTER_ANY_URL;
}
```
If ```urlRegExp``` has been initialized, it will not be replaced with ```SimpleRegex.regexConfiguration.regexStartUrl``` and ```SimpleRegex.regexConfiguration.regexSeparator``` and rule will not be created.

Maybe it will fix #508 and #507

### PR DESCRIPTION
**Pull request by Mizzick**
#510

### CODE REVIEW

File: Extension/browser/safari/lib/converter.js [hunk 1]
```diff
@@ -176,13 +176,13 @@ var SafariContentBlockerConverter = {
         },
 
         _createUrlFilterString: function (filter) {
-            if (filter.urlRegExp) {
-                return filter.urlRegExp.source;
-            }
-
             if (filter.getUrlRuleText() == '||*') {
```
Comment (ameshkov) [inline Extension/browser/safari/lib/converter.js]: I guess we can cover more here:

More FILTER_ANY_URL values:
``
`*`

Comment (Mizzick) [inline Extension/browser/safari/lib/converter.js]: ok
